#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libglvnd
Version  : 1.6.0
Release  : 1
URL      : https://gitlab.freedesktop.org/glvnd/libglvnd/-/archive/v1.6.0/libglvnd-v1.6.0.tar.gz
Source0  : https://gitlab.freedesktop.org/glvnd/libglvnd/-/archive/v1.6.0/libglvnd-v1.6.0.tar.gz
Summary  : Vendor-neutral OpenGL dispatch library vendor interface
Group    : Development/Tools
License  : MIT
Requires: libglvnd-lib = %{version}-%{release}
Requires: libglvnd-license = %{version}-%{release}
BuildRequires : buildreq-meson
BuildRequires : pkgconfig(glproto)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xext)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
libglvnd: the GL Vendor-Neutral Dispatch library
================================================

%package dev
Summary: dev components for the libglvnd package.
Group: Development
Requires: libglvnd-lib = %{version}-%{release}
Provides: libglvnd-devel = %{version}-%{release}
Requires: libglvnd = %{version}-%{release}

%description dev
dev components for the libglvnd package.


%package lib
Summary: lib components for the libglvnd package.
Group: Libraries
Requires: libglvnd-license = %{version}-%{release}

%description lib
lib components for the libglvnd package.


%package license
Summary: license components for the libglvnd package.
Group: Default

%description license
license components for the libglvnd package.


%prep
%setup -q -n libglvnd-v1.6.0
cd %{_builddir}/libglvnd-v1.6.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1676328480
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir

%install
mkdir -p %{buildroot}/usr/share/package-licenses/libglvnd
cp %{_builddir}/libglvnd-v%{version}/src/util/cJSON/LICENSE %{buildroot}/usr/share/package-licenses/libglvnd/033ffa4ac6cd5fd7303f673ed72bb22c981fa435 || :
DESTDIR=%{buildroot} ninja -C builddir install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/EGL/egl.h
/usr/include/EGL/eglext.h
/usr/include/EGL/eglplatform.h
/usr/include/GL/gl.h
/usr/include/GL/glcorearb.h
/usr/include/GL/glext.h
/usr/include/GL/glx.h
/usr/include/GL/glxext.h
/usr/include/GLES/egl.h
/usr/include/GLES/gl.h
/usr/include/GLES/glext.h
/usr/include/GLES/glplatform.h
/usr/include/GLES2/gl2.h
/usr/include/GLES2/gl2ext.h
/usr/include/GLES2/gl2platform.h
/usr/include/GLES3/gl3.h
/usr/include/GLES3/gl31.h
/usr/include/GLES3/gl32.h
/usr/include/GLES3/gl3ext.h
/usr/include/GLES3/gl3platform.h
/usr/include/KHR/khrplatform.h
/usr/include/glvnd/GLdispatchABI.h
/usr/include/glvnd/libeglabi.h
/usr/include/glvnd/libglxabi.h
/usr/lib64/libEGL.so
/usr/lib64/libGL.so
/usr/lib64/libGLESv1_CM.so
/usr/lib64/libGLESv2.so
/usr/lib64/libGLX.so
/usr/lib64/libGLdispatch.so
/usr/lib64/libOpenGL.so
/usr/lib64/pkgconfig/egl.pc
/usr/lib64/pkgconfig/gl.pc
/usr/lib64/pkgconfig/glesv1_cm.pc
/usr/lib64/pkgconfig/glesv2.pc
/usr/lib64/pkgconfig/glx.pc
/usr/lib64/pkgconfig/libglvnd.pc
/usr/lib64/pkgconfig/opengl.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libEGL.so.1
/usr/lib64/libEGL.so.1.1.0
/usr/lib64/libGL.so.1
/usr/lib64/libGL.so.1.7.0
/usr/lib64/libGLESv1_CM.so.1
/usr/lib64/libGLESv1_CM.so.1.2.0
/usr/lib64/libGLESv2.so.2
/usr/lib64/libGLESv2.so.2.1.0
/usr/lib64/libGLX.so.0
/usr/lib64/libGLX.so.0.0.0
/usr/lib64/libGLdispatch.so.0
/usr/lib64/libGLdispatch.so.0.0.0
/usr/lib64/libOpenGL.so.0
/usr/lib64/libOpenGL.so.0.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libglvnd/033ffa4ac6cd5fd7303f673ed72bb22c981fa435
